seed: 42
model:
  which: ViT
  params:
    d_model: 256
    h_dim_mlp: 512
    num_classes: 10
    num_heads: 4
    num_enc_layers: 7
    kernel_size: 4
num_epochs: 200
optim:
  params:
    betas: !!python/tuple
      - 0.9
      - 0.999
    lr: 0.0005
    weight_decay: 0.03
  which: AdamW
