seed: 42
dl:
  params:
    hflip_p: 0.5
    random_crops: True
    translate_p: null
    auto_augment: True
  batch_size: 128
  which: Cifar10
model:
  which: ViT
  params:
    d_model: 768
    h_dim_mlp: 3072
    num_classes: 10
    num_heads: 12
    num_enc_layers: 12
    kernel_size: 16
    dropout_p: 0.1
num_epochs: 200
optim:
  params:
    betas: !!python/tuple
      - 0.9
      - 0.999
    lr: 0.0001
    weight_decay: 0
  which: AdamW
